version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  pg_data: