version: '3.8'
services:
  querovaga:
    container_name: querovaga
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - app-network
    command: ["postgres", "-c", "log_statement=all"]
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pg_data: